# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# Minecraft and NeoForge versions
minecraft_version=26.2
neo_version=26.2.0.75
minecraft_version_range=[26.2,26.3)
neoforgeVersionRange=[26.2.0.0,)

# Parchment no tiene mappings para 26.2 todavia


## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=ntp
# The human-readable display name for the mod.
mod_name=NoNetheriteTemplate
mod_license=MIT
mod_version=17.0.0
mod_group_id=nadiendev.ntp
tag_lanzador=NeoForge
authors=NadienDev
issue_tracker=https://github.com/SrNadien/no-netherite-template/issues

# Dependencies
jei_version=30.29.0.198
# allthemodium_version=8157737
geckolib_version=5.5.4
ato_version_id=8023670
