# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


# Minecraft and NeoForge versions
minecraft_version=26.1.2
neo_version= 26.1.2.53-beta
minecraft_version_range=[26.1, 26.1.1]
neoforgeVersionRange=[26.1.0.8-beta,)

# Partchment
neogradle.subsystems.parchment.minecraftVersion=1.21.11
neogradle.subsystems.parchment.mappingsVersion=2025.12.20


## Mod Properties
mod_id=ntp
mod_name=NoNetheriteTemplate
mod_license=MIT
mod_version=16.1.1
mod_group_id=nadiendev.ntp
tag_lanzador=NeoForge
authors=NadienDev
issue_tracker=https://github.com/SrNadien/no-netherite-template/issues

# Dependencies
jei_version=29.5.0.28
allthemodium_version=8157737
geckolib_version=5.5
ato_version_id=8023670
