modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="ntp"
version="9.0"
displayName="No Netherite Template"
displayURL="https://nadiende.xyz"
logoFile="logo.png"
credits="NadienDev"
authors="SrNadien"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ntp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration