modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL=""
logoFile="logo.png"
credits="${authors}"
authors="${authors}"
description='''This mod removes the Netherite Upgrade Template from the Smithing Table in Minecraft, allowing players to upgrade diamond gear to Netherite without needing the template, simplifying the process of obtaining Netherite gear.'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="${jei_version}"
    ordering="NONE"
    side="BOTH"
