modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="ntp"
version="13"
displayName="No Netherite Template"
displayURL="https://nadiende.xyz"
logoFile="logo.png"
credits="NadienDev"
authors="SrNadien"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.ntp]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ntp]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration